name: CI-CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
        
    - name: Construção da imagem docker
      uses: docker/build-push-action@v3.2.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
           rampss/live-kubenews:V1
           rampss/live-kubenews:latest
